global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: node_exporter
    static_configs:
      - targets: ["127.0.0.1:9100"]

  - job_name: cadvisor
    static_configs:
      - targets: ["127.0.0.1:8088"]

  - job_name: ops_agent
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:9753"]

  - job_name: promtail
    static_configs:
      - targets: ["127.0.0.1:9080"]
